### ISSUE TITLE
Discussion: Purpose of Docker Image

### ISSUE THREAD

**Issue by jdkent** [HBClab/intervention-outcomes#29]
if the purpose of the docker image is to:
- validate the google sheet
- deploy the application

Then changes to the application code are independent (since we are relying on developers to locally test if the application can run, correct?).

If the changes to the application code are independent of deploying the application, we can mount (`-v`) the application code inside the docker container when deploying.
Then we can create the docker image once, push it to dockerhub, and use that docker image every time for validation/deployment.
However, we would want to rebuild the docker image anytime the validation or deployment scripts change.

I'm just a little worried if we continue to build the docker image every time, it will break in a non-trivial way, like how HBClab/RestingState#113 is currently broken (it appears to be related to some python 2/3 incompatibilities), but 
people can still use the previously built docker images even though the current RestingState build is broken.

**Comment by zkhan12** [comment]
This is a good point, so is the suggestion to keep a docker image of the current application (app.R file) and rebuild it whenever the file changes? Seems reasonable to me
