### ISSUE TITLE
[dev] change regex for StudyName

### ISSUE THREAD

**Issue by jdkent** [HBClab/intervention-outcomes#33]
the regular expression is close, but I think a couple edge cases are missing:
- some studies may have a letter after the year: Khan2020a, Khan2020b (solution = `[a-z]{,1}`)
- someone could accidentally add extra characters at the end of the string  (solution = `$`), the dollar sign represents the end of the string.

complete solution: 
`r"^[A-Z][a-z]*[0-9]{4}[a-z]{,1}$"`

**Comment by zkhan12** [comment]
Thanks James! I'll fix the issue
