### ISSUE TITLE
Commit updated csvs?

### ISSUE THREAD

**Issue by jdkent** [HBClab/intervention-outcomes#34]
Currently, if you want to test the app locally, you need to use the csv files located in the `app` directory:

- [InterventionOutcomesRFull.csv](https://github.com/HBClab/intervention-outcomes/blob/5f9e7a3c6aea7088bb6eebe5e3c8ea6c4fb0b648/app/InterventionOutcomesRFull.csv)
- [pano_codebook.csv](https://github.com/HBClab/intervention-outcomes/blob/5f9e7a3c6aea7088bb6eebe5e3c8ea6c4fb0b648/app/pano_codebook.csv)

As the google sheets develop and change, the data in the repo will become outdated, and may lead to unpredictable behavior.

Potential solution:

Update the csvs using circleci.

To do this you need to: 
- create a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with permission to push to a repository
- add the personal access token as a circleci environment variable
- do a git workflow on circleci ([example](https://github.com/HBClab/BetterTaskSwitch/blob/d9f3dd6fc9d5e956f1b6afeb7264f9711976c262/.circleci/config.yml#L51-L66))
  - create bot account
  - git add/commit/push

**Comment by mwvoss** [comment]
I thought these .csv's in the repo were generated directly from the google sheet, such that they are re-generated every time the data from the google sheet is pulled. If that is correct, would that not keep the .csv's updated in the repo?

**Comment by jdkent** [comment]
Good question, the csvs for validation and deployment of the application are pulled from google sheets when circleci is running, but they are thrown away as soon as circleci is done.

The csvs in the repository are remmants from before the application was synced to google sheets.

**Comment by zkhan12** [comment]
Just a follow up, I made a new branch on github (git_updater) that has the code needed to run the weekly data update and push the new data to github, but haven’t configured the account since I don’t have access to the lab github accounts currently. Perhaps someone can utilize the branch to create an access token on a lab account and get this set up in the future.

**Comment by jdkent** [comment]
I don't think we have a lab github account, I've been making up "github accounts" that don't actually exist to differentiate commits made by us versus commits made by circleci.
[Here I made up a name](https://github.com/HBClab/intervention-outcomes/blob/0c452749313ef90c6f6d3ef636ba2d05bed4a26a/.circleci/config.yml#L35), that account does not actually exist on github.

**Comment by jdkent** [comment]
closed by #36
