### ISSUE TITLE
Factor combinations

### ISSUE THREAD

**Issue by mattsodoma** [HBClab/intervention-outcomes#7]
Combination of factors on the user end? Maybe I'm not using it right, but wondering if instead of looking at counts for link type (positive/null/negative), if you can look at link type X dependent variable (each task), or if it can be setup so the user can create their own combinations. Example, the counts for each dependent variable.

**Comment by zkhan12** [comment]
![image](https://user-images.githubusercontent.com/38085378/74482355-f401f600-4e79-11ea-95f0-0535e239b87d.png)
Does this address the issue? The option to add multiple filters should be possible once I update the app. I'll leave the issue open for the meantime.

**Comment by mattsodoma** [comment]
Yes, I believe so. Except was wondering more on the plot side. For example, if I wanted to look at dependent variable VerbalPairedAssociates and VerbalFluency and then wanted to know the different link types associated with them.
