### ISSUE TITLE
Exclude columns

### ISSUE THREAD

**Issue by mattsodoma** [HBClab/intervention-outcomes#8]
Can certain columns be excluded from drop downs? There are certain columns that we didnt code outcomes for, like experimental group 2/3/control group. It would probably be best if we didn't include these in the drop downs for people to create graphs as it might create false data. Although it is still nice for them to be able to see it in the spreadsheet format.

**Comment by zkhan12** [comment]
Just to clarify, you'd like the following columns removed from the drop down options but left in the table below:
- ExperimentalGroup
- ExperimentalGroupN
- ExperimentalGroup2
- ExperimentalGroup2N
- ExperimentalGroup3
- ExperimentalGroup3N
- ControlGroup
- ControlGroupN

Let me know if the list looks correct and I'll make the changes.

**Comment by mattsodoma** [comment]
Leave this one open for now, just wondering if it was an option to turn off certain columns. I'll clarify which columns we want to all turn off. There is an updated sheet as well with some additional columns.

**Comment by mwvoss** [comment]
@mattsodoma I agree it's a great idea to show only a subset of database columns on the page with the plotting tool. How about we only include columns with information for identifying the study and variables that would be used for inclusion of studies of interest, and leave out columns for moderator or outcome variables where all levels of the variable should be included in any plot. 

On this [google doc ](https://docs.google.com/spreadsheets/d/1nWcS0UrfvnPupAwb4uvaMeY7CqmFqIu09F3I9k4ND3s/edit?usp=sharing)(CodeBook tab), I made a first round of answers to this question in Column G. @mattsodoma could you take a look and comment on any changes you'd suggest?

**Comment by mattsodoma** [comment]
Your codebook tab seems reasonable. Would it be worthwhile to show the linktype?

**Comment by mattsodoma** [comment]
Intervention duration may be safe to add as well
